### ISSUE TITLE
Not possible to add import mapping and LUA scripts

### ISSUE THREAD

**Issue by MarkHaakman** [ClickAndMortar/AdvancedCsvConnectorBundle#43] opened 2020-10-21 15:52 UTC
Hi, 
I'm running Akeneo version 4.0.3 and have just added Advanced CSV Connector version 1.8.12 following the instructions on the [Akeneo marketplace](https://marketplace.akeneo.com/extension/advanced-csv-connector).

I can add Export mappings, but when I try to add an Import mapping or LUA script, nothing happens. I can add the label and code on the Create Import Mapping screen, but when I click on Save, the page blinks but not further happens. In the browser console I can see that `POST https://akeneo.xyz.com/reference-data/rest/importMapping/create` results in `500 Internal Server Error`. The same holds for adding a LUA script.

I hope you can help me fix this problem so I can add my Import mappings.
Thanks!

**Comment by MarkHaakman** [comment] 2020-10-22 13:29
Update: now I installed the php-lua package, adding LUA scripts works, but adding Import Mappings still results in a `500 Internal Server Error` in the browser console.

**Comment by lotar** [comment] 2021-01-19 13:38
Same issue here, there's PHP (PDO) Exception:

```
An exception occurred while executing 'INSERT INTO candm_reference_data_importmapping (label, code, mappingAsJson, completeCallback, onlyUpdate, sortOrder, created, updated) VALUES (?, ?, ?, ?, ?, ?, ?, ?)' with params ["test-lotar", "test-lotar", null, null, null, 1, "2021-01-19 13:37:35", "2021-01-19 13:37:35"]:

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'onlyUpdate' cannot be null
```

**Comment by lotar** [comment] 2021-01-19 13:43
Seems to be a problem with lack of default value or SQL specification, either way (since I'm just testing out the bundle) - dirty workaround that solves the issue is setting the default to `0` in file `vendor/clickandmortar/advanced-csv-connector-bundle/Entity/ImportMapping.php` as follows:

![Screen Shot 2021-01-19 at 2 41 47 PM](https://user-images.githubusercontent.com/994234/105042495-9c461480-5a64-11eb-828b-67876da45426.png)

**Comment by simoncarre** [comment] 2021-05-11 08:39
Fixed in last version.

**Closed as completed by simoncarre** 2021-05-11 08:39 UTC
Labels: bug
