### ISSUE TITLE
Badly saved repository

### ISSUE THREAD

**Issue by Philippe-M** [ClickAndMortar/AdvancedCsvConnectorBundle#24] opened 2019-10-07 16:01 UTC
Hello,

I created an export repository with some fields as drop-down lists. In the "Use label" column I select "Yes" and save. I go on another page of the PIM and come back to my export reference. I edit it and modify other values and record.

I go again on another page of the PIM and come back on my referential that I publish. All fields whose "Use label" were "Yes" changed to "No"

**Comment by simoncarre** [comment] 2019-10-17 12:36
Hello @Philippe-M,

Thank you for your tests. The issue is now fixed (release 1.6.7 or 1.7.5).

**Closed as completed** 2019-10-17 12:36 UTC
Labels: bug
